# ~/.config/starship.toml

format = """
$username\
$hostname\
$path\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$battery\
$line_break\
$python\
$golang\
$docker_context\
$kubernetes\
$terraform\
$character"""

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 75
style = "bold red"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
truncation_symbol = 'â€¦/'
home_symbol = "| ó°‹ ~"
style = "blue"

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[âœ–](bold red) "
vimcmd_symbol = "[â®](green)"

# [git_branch]
# format = "[$branch]($style)"
# style = "bright-black"

[git_status]
conflicted = "ïƒ¬ "
deleted = "ï«§"
modified = "ï…‹ "
stashed = "î‰€ "
staged = "ïƒ¾ "
renamed = "ï‘š "
untracked = "ï™ "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = '[${symbol}(${version} )(\($virtualenv\))]($style)'
style = "bright-black"
# should only show up when using virtualenv, disable all other triggers
detect_extensions = []
detect_files = []

[hostname]
ssh_only = true

[golang]
format = '[$symbol($version )($mod_version )]($style)'
symbol = "î˜§ "

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'
detect_files = []

[terraform]
format = "[ï„µ terraform $version]($style)($style) "

[username]
style_user = "bold blue"
style_root = "bold purple"
format = "ïŠ½  [$user]($style) "
disabled = false
# show_always = true

[kubernetes]
format = 'on [ïˆš $context\($namespace\)](bold purple) '
disabled = false
